# fly.toml app configuration file generated for mini-message-board-holy-rain-4603 on 2024-06-21T14:22:21-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mini-message-board-holy-rain-4603'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
